dart compile js -m -o "./test/sample_js_workers/bitcoin_worker.dart.js"         "./test/sample_js_workers/bitcoin_worker.dart"
dart compile js -m -o "./test/sample_js_workers/cache_worker.dart.js"           "./test/sample_js_workers/cache_worker.dart"
dart compile js -m -o "./test/sample_js_workers/echo_worker.dart.js"            "./test/sample_js_workers/echo_worker.dart"
dart compile js -m -o "./test/sample_js_workers/failing_worker.dart.js"         "./test/sample_js_workers/failing_worker.dart"
dart compile js -m -o "./test/sample_js_workers/invalid_worker.dart.js"         "./test/sample_js_workers/invalid_worker.dart"
dart compile js -m -o "./test/sample_js_workers/local_client_worker.dart.js"    "./test/sample_js_workers/local_client_worker.dart"
dart compile js -m -o "./test/sample_js_workers/pi_digits_worker.dart.js"       "./test/sample_js_workers/pi_digits_worker.dart"
dart compile js -m -o "./test/sample_js_workers/prime_worker.dart.js"           "./test/sample_js_workers/prime_worker.dart"
dart compile js    -o "./test/sample_js_workers/rogue_worker.dart.js"           "./test/sample_js_workers/rogue_worker.dart"
dart compile js -m -o "./test/sample_js_workers/sample_worker.dart.js"          "./test/sample_js_workers/sample_worker.dart"
